In [2]:
import tensorflow as tf
import numpy as np

## 张量Tensor  
0D-标量scalar-s=1  
1D-向量vector-s=[1，2，3]  
2D-矩阵matrix-s=[[1,2,3],[4,5,6],[7,8,9]]  
nD-张量tensor-s=[[[[[[......]  

In [2]:
a = tf.constant([1,5],dtype=tf.int64)

print(a)
print(a.dtype)
print(a.shape)    #(2,):一维张量，两个元素

tf.Tensor([1 5], shape=(2,), dtype=int64)
<dtype: 'int64'>
(2,)


将numpy的数据类型转换为Tensor数据类型  
→tf.convert_to_tensor(name,dtype=type)

In [3]:
n = np.arange(0,5)
t = tf.convert_to_tensor(n,dtype=tf.int64)
print(n)
print(t)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


In [4]:
a=tf.zeros([2,3])
b=tf.ones(4)
c=tf.fill([2,2],9)
print(a)
print(b)
print(c)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
tf.Tensor(
[[9 9]
 [9 9]], shape=(2, 2), dtype=int32)


### 生成正态分布的随机数，默认均值为0，标准差为1  
→tf.random.normal(维度，mean=均值，stddev=标准差)  

### 生成截断式正态分布的随机数,生成的随机数在  均值±两倍标准差  之内
→tf.random.truncated_normal(维度，mean=均值，stddev=标准差)

In [5]:
d = tf.random.normal([2,2],mean=0.5,stddev=1)
e = tf.random.truncated_normal([2,2],mean=0.5,stddev=1)
print(d)
print(e)

tf.Tensor(
[[0.24370292 1.0871509 ]
 [1.1051509  0.49397093]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.03549626 1.0260142 ]
 [1.6772411  0.04786518]], shape=(2, 2), dtype=float32)


$$ 标准差\sigma=\sqrt{\frac{\sum_{i=1}^n(x_i-\bar x)}{n}} \quad $$

In [6]:
# 生成均匀分布的随机数
# →tf.random.uniform(维度,minval=最小值,maxval=最大值)

f = tf.random.uniform([2,2],minval=0,maxval=1)
print(f)

tf.Tensor(
[[0.6149658  0.04074144]
 [0.8912672  0.8597696 ]], shape=(2, 2), dtype=float32)


#  常用函数  
强制Tensor转换为该数据类型  
→tf.cast(张量名,dtype=数据类型)  
计算张量维度上元素的最小值  
→tf.reduce_min(name)  
计算张量维度上元素的最大值  
→tf.reduce_max(name)  

In [7]:
x1 = tf.constant([1.,2.,3.],dtype=tf.float64)
print(x1)
x2 = tf.reduce_min(x1)
print(x2)
x3 = tf.reduce_max(x1)
print(x3)

tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(3.0, shape=(), dtype=float64)


##  axis
tf.math.reduce_mean(张量名，axis=操作轴)：计算张量沿着指定维度的平均值  
tf.math.reduce_sum(张量名，axis=操作轴)：计算张量沿着指定维度的和  
tf.math.reduce_max(张量名，axis=操作轴)：计算张量沿着指定维度的最小值  
tf.math.reduce_min(张量名，axis=操作轴)：计算张量沿着指定维度的最大值  

In [8]:
x=tf.constant([[1,2,3],[2,3,4],[7,6,5],[0,0,0]],dtype=tf.float32)
print(tf.math.reduce_mean(x,axis=0))
print(tf.math.reduce_sum(x,axis=0))
print(tf.math.reduce_max(x,axis=0))
print(tf.math.reduce_min(x,axis=0))

tf.Tensor([2.5  2.75 3.  ], shape=(3,), dtype=float32)
tf.Tensor([10. 11. 12.], shape=(3,), dtype=float32)
tf.Tensor([7. 6. 5.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


## Variable
tf.Variable()将变量标记为“可训练”，被标记的变量会在方向传播中记录梯度信息。在神经网络中，常使用该函数标记待训练参数。

In [9]:
w = tf.Variable(tf.random.normal([2,3],mean=0,stddev=1))
print(w)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[-0.25704044, -0.85390633,  1.3285797 ],
       [-0.14725108,  0.2442307 ,  2.689173  ]], dtype=float32)>


## 四则运算
tf.add: 实现两张量对应元素的相加  
tf.subtract:实现两张量对应元素的相减  
tf.multiply:实现两张量对应元素的相乘  
tf.divide:实现两张量对应元素的相除  
只有维度相同的张量才能进行四则运算  

In [10]:
a=tf.ones([1,3],dtype=tf.float32)
b=tf.fill([1,3],3.)
print(tf.add(a,b))
print(tf.subtract(a,b))
print(tf.multiply(a,b))
print(tf.divide(a,b))

tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float32)
tf.Tensor([[-2. -2. -2.]], shape=(1, 3), dtype=float32)
tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
tf.Tensor([[0.33333334 0.33333334 0.33333334]], shape=(1, 3), dtype=float32)


## 平方、次方和开方
tf.square(张量名)：计算张量的平方  
tf.pow(张量名，n次方数)：计算张量的n次方  
tf.sqrt(张量名)：计算张量的开方 

In [15]:
x=tf.fill([1,2],3.)
print(tf.square(x))
print(tf.pow(x,3))
print(tf.pow(x,0.5))
print(tf.sqrt(x))

tf.Tensor([[9. 9.]], shape=(1, 2), dtype=float32)
tf.Tensor([[27. 27.]], shape=(1, 2), dtype=float32)
tf.Tensor([[1.7320508 1.7320508]], shape=(1, 2), dtype=float32)
tf.Tensor([[1.7320508 1.7320508]], shape=(1, 2), dtype=float32)


 
## 矩阵相乘
tf.linalg.matmul(矩阵1，矩阵2)

In [18]:
a=tf.ones([3,2],dtype=tf.float32)
b=tf.fill([2,3],3.)
print(tf.linalg.matmul(a,b))

tf.Tensor(
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]], shape=(3, 3), dtype=float32)


## tf.data.Dataset.from_tensor_slices

切分输入张量的第一维度，生成输入特征标签对，构建数据集。使用方法是：  
data=tf.data.Dataset.from_tensor_slices((特征，标签))，输入的数据类型可以是numpy或tensor。

In [21]:
features=tf.constant([11,12,13,14],dtype=tf.float32)
label=tf.constant([1,2,3,4],dtype=tf.float32)
dataset=tf.data.Dataset.from_tensor_slices((features,label))
print(dataset)
for element in dataset:
    print(element)

<TensorSliceDataset shapes: ((), ()), types: (tf.float32, tf.float32)>
(<tf.Tensor: shape=(), dtype=float32, numpy=11.0>, <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)
(<tf.Tensor: shape=(), dtype=float32, numpy=12.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2.0>)
(<tf.Tensor: shape=(), dtype=float32, numpy=13.0>, <tf.Tensor: shape=(), dtype=float32, numpy=3.0>)
(<tf.Tensor: shape=(), dtype=float32, numpy=14.0>, <tf.Tensor: shape=(), dtype=float32, numpy=4.0>)


## tf.GradientTape(persistent=False, watch_accessed_variables=True)
这是一个功能很强大的类，主要功能是用于计算梯度和雅克比矩阵。  
persistent指资源持久性，默认情况下它是False；watch_accessed_variables用于声明变量是否能求导，默认情况下所有变量都能被求导。  

In [24]:
# with tf.GradientTaps() as tape:  
#       若干个计算过程  
# grad=tape.gradient(函数，对谁求导)  
with tf.GradientTape() as tape:
    w = tf.Variable(tf.constant(3.0))
    loss = tf.pow(w,2)
grad = tape.gradient(loss,w)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


## 枚举
enumerate是python的内置函数，它可遍历列表、元祖、字典的每一个元素，组合为：索引号和元素，常在for循环中使用。

In [25]:
seq=['one','two','three']
for i, element in enumerate(seq):
    print(i,element)

0 one
1 two
2 three


## 独热编码

在分类问题中，常用one-hot encoding制作标签。  
举一个例子，我们有3个类别0,1,2，类别0的独热码为100，类别1为010，类别2为001。  
也就是说，独热码表示了某一个类别的分布概率。  

tf.one_hot(待转化数据，depth=几分类)，待转化数据可以是Tensor或列表  

In [30]:
classes=3
label=tf.constant([1,0,2]) #Tensor
#label=[1,2,1] #列表
output=tf.one_hot(label,classes)
print(output)

tf.Tensor(
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


## tf.nn.softmax

作用是使网络的输出符合概率分布，并且输出概率的和为1。

$$ Softmax(y_i)=\frac{e^{y_i}}{\sum_{j=0}^ne^{y_i}}  $$

In [31]:
x=tf.constant([1.01,2.01,-0.66])
y=tf.nn.softmax(x)
print(y)
print(tf.reduce_sum(y))

tf.Tensor([0.25598174 0.69583046 0.04818781], shape=(3,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


## assign_sub
赋值操作更新参数的值并返回。  
调用assign_sub前，先用tf.Variable定义变量可训练  
w.assign_sub(w要自减的内容)

In [32]:
w = tf.Variable(4)
w.assign_sub(1)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


## tf.math.argmax
作用是返回张量沿指定维度最大值的索引号。  
tf.math.argmax(张量，axis=操作轴)，其中张量的数据类型可以是Tensor、列表或numpy类型，默认axis=0纵向。  

In [3]:
test = tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(test)
print(tf.argmax(test,0))#返回每一行的最大值索引
print(tf.argmax(test,1))#返回每一行的最大值索引

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
tf.Tensor([2 2 2 2], shape=(4,), dtype=int64)
tf.Tensor([3 3 3], shape=(3,), dtype=int64)


## np.vstack()
将两个数组按垂直方向叠加

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


## np.mgrid[]
np.mgrid[起始值:结束值:步长,起始值:结束值:步长,.....]
## .ravel()
x.ravel()把x拉直变为一维数组
## np.c_[]
使返回的间隔数值点配对

In [5]:
x,y = np.mgrid[1:3:1,2:4:0.5]
grid = np.c_[x.ravel(),y.ravel()]
print("x:",x)
print("y:",y)
print('grid:\n',grid)

x: [[1. 1. 1. 1.]
 [2. 2. 2. 2.]]
y: [[2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5]]
grid:
 [[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]]
